### PR TITLE
fixed margins for smaller screen sizes for flavor archetype

### PR DESCRIPTION
**Pull request by mdaxtman**
@coopy @paulathevalley @tptee Fixed errors with margins for archetype on smaller screens

### CODE REVIEW

**Comment by mdaxtman** [comment]
let me know what you think @paulathevalley @tptee

**Comment by coopy** [comment]
Looks good to me - assigning Paula to give final :+1:

**Comment by paulathevalley** [comment]
rocket-launch5

**Comment by coopy** [comment]
^ It's a thing of beauty.

**Pull request merged**
